### ISSUE TITLE
Feature Request: Allow SolinstFileReader to read automatically de file when instantiating

### ISSUE THREAD

**Issue by jnsebgosselin** [x-malet/HydroSensorReader#21]
The `wait_read` argument of the `AbstractFileReader` allow to read automatically the data from the a file when instantiating a reader.

> :param wait_read: if wait_read is False, will wait to read the file content. This is usefull for hierarchi-class
        see file_reader.compagny_file_reader.solinst_file_reader.py for an example

(We shoudl read here _if wait_read is **True**, will wait to read the file content_)

However, this argument is not available in the  `SolinstFileReader ` and its value is set to `True` by default :

```python
class SolinstFileReader(TimeSeriesFileReader):
    def __init__(self, file_path: str = None, header_length: int = 10):
        super().__init__(
            file_path, header_length, encoding='cp1252', wait_read=False)
```
We need to explicitly call `read_file` after instantiating a `SolinstFileReader`, or else data are not read, which is confusing.

I suggest that:
- We add the `wait_read` as an argument of the `SolinstFileReader`
- We set the value to `False` by default.

@x-malet What do you think?

**Comment by x-malet** [comment]
Good idea. I think that I unable it by default to force the programmer to use the `read_file` method. It's a good idea to use this parameter for batch processing!

**Comment by jnsebgosselin** [comment]
Ok super, je vais faire une PR.

**Comment by x-malet** [comment]
It's the same think for the `XLSHannaFileReader` class...^^ can you change that to??

**Comment by jnsebgosselin** [comment]
> 
> 
> It's the same think for the `XLSHannaFileReader` class...^^ can you change that to??

Sure

**Comment by x-malet** [comment]
Hum....je viens de voir comment faire que ca marche vraiment bien...

1. Ajouter `wait_read` aux classes spécialisé (`XLSHannaFileReader`, `SolinstFileReader`,..)
2. Ajouter à la classe parent imédiate (`TimeSeriesFileReader`) l'élément suivant:
`if not wait_read:
            self.read_file()`
3. On peut alors enlever les read_file() !!!

**Comment by x-malet** [comment]
Si on utilise Python 3 on peut utiliser [__init_subclass__](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__)

**Comment by jnsebgosselin** [comment]
> 
> 
> Si on utilise Python 3 on peut utiliser [**init_subclass**](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__)

Cool, Je vais essayer ça!

**Comment by x-malet** [comment]
Je pense quand même que la première méthode est plus simple! (la méthode en 3 temps!). Init_subclass implique de transformer des méthodes en classmethod... Ça risque des long... Pour pas grand chose...lol

**Comment by jnsebgosselin** [comment]
lol oui c'est ce que je me suis rendu compte... c'était moins simple que ça en avait l'air à première vue.
